<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace>Smolla.Realtime.Host</RootNamespace>
        <AssemblyName>Smolla.Realtime.Host</AssemblyName>
        <UserSecretsId>smolla-realtime-host</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

</Project>
